import { type NextPage } from "next";
import Head from "next/head";
///////////////////
// Frontend Code //
//////////////////

import Image from "next/image";
import productImage from "../imgs/monitor.jpg";

// 🔧 Todo #1: Import backend functions

const Home: NextPage = () => {
  // 🔧 Todo #2: Start connecting server here
  // 🔧 Todo #3: Render the data on the page
  // 🔧 Todo #4: Fix the product detail data type since BE changes
  return (
    <>
      <Head>
        <title>My Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex w-1/2 flex-col justify-center gap-12 rounded-xl bg-white p-16">
          <div className="flex items-center">
            <div className="flex-2 mr-8 flex flex-col justify-between">
              <h1 className="my-4 text-3xl font-bold">Product Name</h1>
              <Image
                src={productImage}
                alt="Product Image"
                className="mb-4 rounded-xl"
                width={300}
                height={300}
              />
            </div>
            <div className="flex-1 text-[30px]">
              <div className="mb-4">
                <span className="font-bold">Category: </span>
                <span>-</span>
              </div>
              <div className="mb-4">
                <span className="font-bold">Description: </span>
                <p className="text-gray-700">-</p>
              </div>
              <div className="mb-4 flex items-center">
                <span className="mr-2 font-bold">Price: </span>
                <div className="flex items-center">฿ -</div>
              </div>
              <div className="mb-4 flex items-center">
                <span className="mr-2 font-bold">Ratings: </span>
                <div className="flex items-center">-</div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
